apiVersion: v1
kind: Service
metadata:
  name: tareasadmin-service
  namespace: tareasadmin
  labels:
    app: tareasadmin
spec:
  type: NodePort
  selector:
    app: tareasadmin
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      nodePort: 30080
      #prueba del commit
      
